site_name: Common Fund Data Ecosystem Use Cases

repo_url: https://github.com/nih-cfde/usecases

theme:
  name: material
  palette:
    primary: white
  features:
    - tabs
  logo: images/CFDE-logo.png
  custom_dir: docs/templates

docs_dir: docs


plugins:
  - search: # necessary for search to work
      separator: '[\s\-\.]+'
  - awesome-pages
  - git-revision-date-localized
  - htmlproofer
markdown_extensions:
- admonition
- pymdownx.emoji
- codehilite:
    guess_lang: false
- toc:
    permalink: true
extra:
  hypothesis: true
extra_css:
  - stylesheets/extra.css
