site_name: Common Fund Data Ecosystem Use Cases

repo_url: https://github.com/nih-cfde/usecases

theme:
  name: material
  palette:
    primary: white
  features:
    - tabs
  logo: images/CFDE-logo.png

docs_dir: docs

nav:
  - Home: index.md
  - Glossary: metadocs/glossary.md
  - Use Cases:
    - UC0001 Researcher Browse and Filter: use-cases/uc0001-researcher-browse-and-filter.md
    - UC0002 Explore data availability to build policy: use-cases/uc0002-explore-data-availability-to-build-policy.md
    - UC0003 Monitor Data Releases as a Data Custodian: use-cases/uc0003-monitor-data-releases-as-a-data-custodian.md
    - UC0004 Create a Data Release: use-cases/uc0004-create-a-data-release.md
    - UC0005 Researcher Browse and Filter- complex: use-cases/uc0005-researcher-browse-and-filter-complex.md
  - Personas:
    - CFDE Clinical Researcher: personas/cfde-clinical-researcher.md
    - Clinical Researcher: personas/clinical-researcher.md
    - Data Administrator: personas/data-administrator.md
    - Data Custodian: personas/data-custodian.md
    - Data Scientist: personas/data-scientist.md
    - Program Officer: personas/program-officer.md
  - Objectives:
    - Create Data Release: objectives/create-data-release.md
    - Discover Datasets: objectives/discover-datasets.md
    - Multi DCC Comparison: objectives/multi-dcc-comparison.md
    - Single DCC Release: objectives/single-dcc-release.md
    - Single DCC Usage: objectives/single-dcc-usage.md
  - Tasks:
    - T0001 Access Cfde Interface: user-tasks/t0001-access-cfde-interface.md
    - T0002 Explore Program Links: user-tasks/t0002-explore-program-links.md
    - T0003 Export A File Of Results: user-tasks/t0003-export-a-file-of-results.md
    - T0004 Search Within Data Set Descriptions: user-tasks/t0004-search-within-dataset-descriptions.md
    - T0005 Searchfilter Data Sets By Type Terms: user-tasks/t0005-searchfilter-data-sets-by-type-terms.md
    - T0006 Searchfilter Data Sets By Anatomic Terms: user-tasks/t0006-searchfilter-data-sets-by-anatomic-terms.md
    - T0007 Summarize All Datatypes Hosted By Cf Program X: user-tasks/t0007-summarize-all-datatypes-hosted-by-cf-program-x.md
    - T0008 Summarize Fairness Scores By Cf Program X Over Time: user-tasks/t0008-summarize-fairness-scores-by-cf-program-x-over-time.md
    - T0009 Summarize Fairness Scores By Cf Program X: user-tasks/t0009-summarize-fairness-scores-by-cf-program-x.md
    - T0010 Visualize A Table Of All Projects That Match Query: user-tasks/t0010-visualize-a-table-of-all-projects-that-match-query.md
    - T0011 Searchfilter Common Fund Programs By Anatomic Terms: user-tasks/t0011-searchfilter-common-fund-programs-by-anatomic-terms.md
    - T0012 Search Filter Common Fund Programs By Type Terms: user-tasks/t0012-search-filter-common-fund-programs-by-type-terms.md
    - T0013 Review C2M2 Documentation: user-tasks/t0013-review-c2m2-documentation.md
    - T0014 Install Cfde Ingest Tool: user-tasks/t0014-install-cfde-ingest-tool.md
    - T0015 Ingest Candidate Data Release: user-tasks/t0015-ingest-candidate-data-release.md
    - T0016 DCC Review Approve Reject Ingest Results: user-tasks/t0016-dcc-review-approve-reject-ingest-results.md
  - Requirements:
    - R00001 The Interface Will Support Gui Web Access To End Users: requirements/r00001-the-interface-will-support-gui-web-access-to-end-users.md
    - R00002 The Interface Will Support User Authentication: requirements/r00002-the-interface-will-support-user-authentication.md
    - R00003 The Interface Will Support The Selection Of An Uberon Term Of Interest: requirements/r00003-the-interface-will-support-the-selection-of-an-uberon-term-of-interest.md
    - R00004 The C2M2 Model Will Support Information Relating Uberon Terms To CF Programs: requirements/r00004-the-c2m2-model-will-support-information-relating-uberon-terms-to-cf-programs.md
    - R00005 The Catalog Will Store Information Relating Uberon Terms To CF Programs: requirements/r00005-the-catalog-will-store-information-relating-uberon-terms-to-cf-programs.md
    - R00006 The Interface Will Support The Selection Of An Assay Type Term Of Interest: requirements/r00006-the-interface-will-support-the-selection-of-an-assay-type-term-of-interest.md
    - R00007 The C2M2 Model Will Support Information Relating Assay Types To CF Programs: requirements/r00007-the-c2m2-model-will-support-information-relating-assay-types-to-cf-programs.md
    - R00008 The Catalog Will Store Information Relating Assay Types To CF Programs: requirements/r00008-the-catalog-will-store-information-relating-assay-types-to-cf-programs.md
    - R00009 The Interface Will Support Free Text Search Of Results: requirements/r00009-the-interface-will-support-free-text-search-of-results.md
    - R00010 The Catalog Will Store Information Relating Projects To CF Programs: requirements/r00010-the-catalog-will-store-information-relating-projects-to-cf-programs.md
    - R00011 The C2M2 Model Will Support Information Relating Projects To CF Programs: requirements/r00011-the-c2m2-model-will-support-information-relating-projects-to-cf-programs.md
    - R00012 The Interface Will Render Tables And Plots To Display Filtered Data: requirements/r00012-the-interface-will-render-tables-and-plots-to-display-filtered-data.md
    - R00013 The Interface Will Support Links To Original Data Sources Within The Results: requirements/r00013-the-interface-will-support-links-to-original-data-sources-within-the-results.md
    - R00014 The Interface Will Support End User Download Of Tables And Figures In Common Formats: requirements/r00014-the-interface-will-support-end-user-download-of-tables-and-figures-in-common-formats.md
    - R00015 The Interface Will Support The Selection Of A Species Term Of Interest: requirements/r00015-the-interface-will-support-the-selection-of-a-species-term-of-interest.md
    - R00016 The C2M2 Model Will Support Information Relating Species Terms To CF Programs: requirements/r00016-the-c2m2-model-will-support-information-relating-species-terms-to-cf-programs.md
    - R00017 The Catalog Will Store Information Relating Species Terms To CF Programs: requirements/r00017-the-catalog-will-store-information-relating-species-terms-to-cf-programs.md
    - R00018 The Interface Will Support The Selection Of A CF Program Of Interest: requirements/r00018-the-interface-will-support-the-selection-of-a-cf-program-of-interest.md
    - R00019 The C2M2 Model Will Support Information Relating Fair Metrics To CF Programs: requirements/r00019-the-c2m2-model-will-support-information-relating-fair-metrics-to-cf-programs.md
    - R00020 The Catalog Will Store Information Relating Fair Metrics To CF Programs: requirements/r00020-the-catalog-will-store-information-relating-fair-metrics-to-cf-programs.md
    - R00021 The Interface Will Support The Selection Of A Time Period Of Interest: requirements/r00021-the-interface-will-support-the-selection-of-a-time-period-of-interest.md
    - R00022 The C2M2 Documentation Is Publicly Available: requirements/r00022-the-c2m2-documentation-is-publicly-available.md
    - R00023 The CFDE Ingest Tool Is Publicly Available: requirements/r00023-the-cfde-ingest-tool-is-publicly-available.md
    - R00024 The CFDE Ingest Tool Can Be Installed: requirements/r00024-the-cfde-ingest-tool-can-be-installed.md
    - R00025 The CFDE Ingest Tool Supports User Authentication: requirements/r00025-the-cfde-ingest-tool-supports-user-authentication.md
    - R00026 The CFDE Ingest Tool Requires Authorization: requirements/r00026-the-cfde-ingest-tool-requires-authorization.md
    - R00027 The CFDE Ingest Tool Can Ingest Data In The C2M2 Data Model: requirements/r00027-the-cfde-ingest-tool-can-ingest-data-in-the-c2m2-data-model.md
    - R00028 The CFDE Ingest Tool Rejects Malformed C2M2 Metadata: requirements/r00028-the-cfde-ingest-tool-rejects-malformed-c2m2-metadata.md
    - R00029 The Interface Allows Data Administrators To Review The Ingest Results: requirements/r00029-the-interface-allows-data-administrators-to-review-the-ingest-results.md
    - R00030 The Interface Allows Data Administrators To Approve A Recent Candidate Data Release: requirements/r00030-the-interface-allows-data-administrators-to-approve-a-recent-candidate-data-release.md
    - R00031 When Data Release Is Approved By Data Administrator It Is Marked For Review By CFDE: requirements/r00031-when-data-release-is-approved-by-data-administrator-it-is-marked-for-review-by-cfde.md
    - R00032 The C2M2 model will support links to original data sources: requirements/r00032-the-c2m2-model-will-support-links-to-original-data-sources.md
    - R00033 The catalog will links to original data sources: requirements/r00033-the-catalog-will-links-to-original-data-sources.md
  - Contributing: metadocs/contributing.md

plugins:
  - search # necessary for search to work
  - awesome-pages
markdown_extensions:
- admonition
- pymdownx.emoji
- codehilite:
    guess_lang: false
- toc:
    permalink: true
extra:
  hypothesis: true
extra_css:
  - stylesheets/extra.css
